M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu20.04.1} date Tue Aug 13 10:52:44 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-13T10:52:44+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.750
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X12.563Y6.0
T2
X14.563Y6.0
T3
X-4.0Y-8.144
X-4.0Y-22.144
X19.0Y-8.144
X19.0Y-10.714
X19.0Y-19.604
X19.0Y-22.144
M30
